title = "Humans Deserve"
languageCode = "en-us"
defaultContentLanguage = "en"
timeZone = "America/Chicago"
copyright = "© 2023-present, Humans Deserve"

theme = "PaperMod"

baseURL = 'https://humansdeserve.org/'
enableRobotsTXT = true
paginate = 15

disableKinds = ["taxonomyTerm"]

[params]
description = "No ifs, ands or buts"
defaultTheme = "auto"
showReadingTime = true
showCodeCopyButtons = true
showPostNavLinks = true
env = "development"
keywords = []

[params.assets]
disableFingerprinting = true

# Shown on the home page
socialIcons = [
    { name = "github", url = "https://github.com/humansdeserve/" },
]

# Configure the home page
[params.profileMode]
enabled = true
title = "Humans Deserve"
subtitle = "No ifs, ands or buts"
imageUrl = "/profile-image.svg"
